# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bf9a39abb86041d58b98c8004624e1e"
application_url = "https://headless-react-git-app-deep-shopifys-projects.vercel.app"
embedded = true
name = "demo-react-app"
handle = "demo-react-app-6"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_products,read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://headless-react-git-app-deep-shopifys-projects.vercel.app/auth/callback",
  "https://headless-react-git-app-deep-shopifys-projects.vercel.app/auth/shopify/callback",
  "https://headless-react-git-app-deep-shopifys-projects.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "react-demo-store-2024.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
